//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.18052
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Codeer.Friendly.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Codeer.Friendly.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   This has already been executed. An Async object can only be used once. To call an operation more than once, create a new Async object. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorAsyncDuplicativeCall {
            get {
                return ResourceManager.GetString("ErrorAsyncDuplicativeCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Argument number {0} is incorrect. The namespace or class name could be a likely cause. Please double-check the syntax used for creating the argument. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorDefinitionArgument {
            get {
                return ResourceManager.GetString("ErrorDefinitionArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Argument number {0} is incorrect. The specified AppVar belongs to a separate AppFriend&apos;s variable pool. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorDifferentAppFriendVar {
            get {
                return ResourceManager.GetString("ErrorDifferentAppFriendVar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   It is the object that has been disposed already. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorDisposedObject {
            get {
                return ResourceManager.GetString("ErrorDisposedObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid completion specification. This method should not generally be called. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorInvalidCompleted {
            get {
                return ResourceManager.GetString("ErrorInvalidCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Illegal static function call. Operation information requires a type. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorInvalidStaticCall {
            get {
                return ResourceManager.GetString("ErrorInvalidStaticCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An exception occurred inside the target application.
        ///[Message]
        ///{0}
        ///[Exception type]
        ///{1}
        ///[Error cause]
        ///{2}
        ///[Stack trace]
        ///{3}
        ///[Help]
        ///{4} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ExceptionInfoFormat {
            get {
                return ResourceManager.GetString("ExceptionInfoFormat", resourceCulture);
            }
        }
    }
}
